"""create backend schema

Revision ID: 10ba86abea77
Revises: None
Create Date: 2026-07-20 15:24:49.530597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10ba86abea77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_impact_measurements',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('measurement_type', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_business_impact_measurements_id'), 'business_impact_measurements', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_business_impact_measurements_org_id'), 'business_impact_measurements', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('case_studies',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('company_size', sa.String(length=50), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('solution_summary', sa.Text(), nullable=False),
    sa.Column('key_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roi_percentage', sa.Float(), nullable=True),
    sa.Column('time_to_value_days', sa.Integer(), nullable=True),
    sa.Column('agents_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connectors_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('testimonial', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_title', sa.String(length=200), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_case_studies_id'), 'case_studies', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_case_studies_industry'), 'case_studies', ['industry'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_case_studies_org_id'), 'case_studies', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('customer_feedback',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('feature_area', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_customer_feedback_id'), 'customer_feedback', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_customer_feedback_org_id'), 'customer_feedback', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('customer_health',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('usage_score', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('satisfaction_score', sa.Integer(), nullable=False),
    sa.Column('support_score', sa.Integer(), nullable=False),
    sa.Column('adoption_score', sa.Integer(), nullable=False),
    sa.Column('last_calculated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('positive_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_customer_health_id'), 'customer_health', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_customer_health_org_id'), 'customer_health', ['org_id'], unique=True, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_customer_health_status'), 'customer_health', ['status'], unique=False, schema='eyex_backend')
    op.create_table('customer_success_reports',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('usage_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adoption_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_customer_success_reports_id'), 'customer_success_reports', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_customer_success_reports_org_id'), 'customer_success_reports', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('industry_solutions',
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_problems', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_use_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_agents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_connectors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('demo_scenarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roi_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('case_studies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing_guidance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_industry_solutions_id'), 'industry_solutions', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_industry_solutions_industry'), 'industry_solutions', ['industry'], unique=True, schema='eyex_backend')
    op.create_table('leads',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_leads_email'), 'leads', ['email'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_leads_id'), 'leads', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_leads_status'), 'leads', ['status'], unique=False, schema='eyex_backend')
    op.create_table('market_opportunities',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_approach', sa.Text(), nullable=True),
    sa.Column('competitive_landscape', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_market_opportunities_id'), 'market_opportunities', ['id'], unique=False, schema='eyex_backend')
    op.create_table('marketplace_revenue',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('developer_payout', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_marketplace_revenue_agent_id'), 'marketplace_revenue', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_marketplace_revenue_id'), 'marketplace_revenue', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_marketplace_revenue_org_id'), 'marketplace_revenue', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('partners',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('partner_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('integration_status', sa.String(length=50), nullable=False),
    sa.Column('integration_notes', sa.Text(), nullable=True),
    sa.Column('revenue_share_percent', sa.Float(), nullable=False),
    sa.Column('joint_customers', sa.Integer(), nullable=False),
    sa.Column('pipeline_value', sa.Float(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_partners_id'), 'partners', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_partners_partner_type'), 'partners', ['partner_type'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_partners_status'), 'partners', ['status'], unique=False, schema='eyex_backend')
    op.create_table('retention_workflows',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_retention_workflows_id'), 'retention_workflows', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_retention_workflows_org_id'), 'retention_workflows', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('roi_calculators',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('calculator_type', sa.String(length=100), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_roi_calculators_id'), 'roi_calculators', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_roi_calculators_org_id'), 'roi_calculators', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_yearly', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('max_tasks_per_month', sa.Integer(), nullable=False),
    sa.Column('max_api_calls_per_month', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('support_level', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_subscription_plans_id'), 'subscription_plans', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True, schema='eyex_backend')
    op.create_table('usage_based_billing',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_executions', sa.Integer(), nullable=False),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('storage_gb_used', sa.Float(), nullable=False),
    sa.Column('compute_hours', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_usage_based_billing_id'), 'usage_based_billing', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_usage_based_billing_org_id'), 'usage_based_billing', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('usage_metrics',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_usage_metrics_id'), 'usage_metrics', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_usage_metrics_org_id'), 'usage_metrics', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_users_email'), 'users', ['email'], unique=True, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_users_id'), 'users', ['id'], unique=False, schema='eyex_backend')
    op.create_table('enterprise_pricing',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('custom_monthly_price', sa.Float(), nullable=True),
    sa.Column('custom_annual_price', sa.Float(), nullable=True),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('contract_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_per_month', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Integer(), nullable=True),
    sa.Column('custom_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('negotiated_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['eyex_backend.subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_enterprise_pricing_id'), 'enterprise_pricing', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_enterprise_pricing_org_id'), 'enterprise_pricing', ['org_id'], unique=True, schema='eyex_backend')
    op.create_table('organizations',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['eyex_backend.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_organizations_id'), 'organizations', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_organizations_slug'), 'organizations', ['slug'], unique=True, schema='eyex_backend')
    op.create_table('partnership_integrations',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('integration_name', sa.String(length=200), nullable=False),
    sa.Column('integration_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('auth_method', sa.String(length=100), nullable=True),
    sa.Column('sync_frequency', sa.String(length=50), nullable=True),
    sa.Column('data_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['eyex_backend.partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_partnership_integrations_id'), 'partnership_integrations', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_partnership_integrations_partner_id'), 'partnership_integrations', ['partner_id'], unique=False, schema='eyex_backend')
    op.create_table('pipeline_deals',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('competitor', sa.String(length=200), nullable=True),
    sa.Column('loss_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['eyex_backend.leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_pipeline_deals_id'), 'pipeline_deals', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_pipeline_deals_lead_id'), 'pipeline_deals', ['lead_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_pipeline_deals_org_id'), 'pipeline_deals', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_pipeline_deals_stage'), 'pipeline_deals', ['stage'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_pipeline_deals_status'), 'pipeline_deals', ['status'], unique=False, schema='eyex_backend')
    op.create_table('customer_onboarding',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('assigned_csm', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_go_live', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['eyex_backend.pipeline_deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_customer_onboarding_current_stage'), 'customer_onboarding', ['current_stage'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_customer_onboarding_id'), 'customer_onboarding', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_customer_onboarding_org_id'), 'customer_onboarding', ['org_id'], unique=True, schema='eyex_backend')
    op.create_table('deal_activities',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=200), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['eyex_backend.pipeline_deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_deal_activities_deal_id'), 'deal_activities', ['deal_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_deal_activities_id'), 'deal_activities', ['id'], unique=False, schema='eyex_backend')
    op.create_table('enterprise_demos',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('presenter_id', sa.UUID(), nullable=False),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['eyex_backend.pipeline_deals.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['eyex_backend.leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_enterprise_demos_id'), 'enterprise_demos', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_enterprise_demos_org_id'), 'enterprise_demos', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_enterprise_demos_scheduled_at'), 'enterprise_demos', ['scheduled_at'], unique=False, schema='eyex_backend')
    op.create_table('organization_members',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['eyex_backend.organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['eyex_backend.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_organization_members_id'), 'organization_members', ['id'], unique=False, schema='eyex_backend')
    op.create_table('sales_predictions',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('actual_outcome', sa.Float(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['eyex_backend.pipeline_deals.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['eyex_backend.leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_sales_predictions_id'), 'sales_predictions', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_sales_predictions_org_id'), 'sales_predictions', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['eyex_backend.organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['eyex_backend.subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_subscriptions_id'), 'subscriptions', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False, schema='eyex_backend')
    op.create_table('workspaces',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['eyex_backend.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_workspaces_id'), 'workspaces', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_workspaces_slug'), 'workspaces', ['slug'], unique=False, schema='eyex_backend')
    op.create_table('agent_configs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_role', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['eyex_backend.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_configs_id'), 'agent_configs', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_configs_workspace_id'), 'agent_configs', ['workspace_id'], unique=False, schema='eyex_backend')
    op.create_table('api_keys',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['eyex_backend.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['eyex_backend.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_api_keys_id'), 'api_keys', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False, schema='eyex_backend')
    op.create_table('invoices',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_invoice_id', sa.String(length=256), nullable=True),
    sa.Column('invoice_url', sa.String(length=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['eyex_backend.organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['eyex_backend.subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_invoices_id'), 'invoices', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_invoices_organization_id'), 'invoices', ['organization_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False, schema='eyex_backend')
    op.create_table('onboarding_tasks',
    sa.Column('onboarding_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_id'], ['eyex_backend.customer_onboarding.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_onboarding_tasks_id'), 'onboarding_tasks', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_onboarding_tasks_onboarding_id'), 'onboarding_tasks', ['onboarding_id'], unique=False, schema='eyex_backend')
    op.create_table('task_executions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('agent_role', sa.String(length=100), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['eyex_backend.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['eyex_backend.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_task_executions_id'), 'task_executions', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_task_executions_session_id'), 'task_executions', ['session_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_task_executions_status'), 'task_executions', ['status'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_task_executions_workspace_id'), 'task_executions', ['workspace_id'], unique=False, schema='eyex_backend')
    op.create_table('usage_records',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['eyex_backend.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_usage_records_id'), 'usage_records', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_usage_records_recorded_at'), 'usage_records', ['recorded_at'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_usage_records_workspace_id'), 'usage_records', ['workspace_id'], unique=False, schema='eyex_backend')
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['eyex_backend.users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['eyex_backend.workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_workspace_members_id'), 'workspace_members', ['id'], unique=False, schema='eyex_backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eyex_backend_workspace_members_id'), table_name='workspace_members', schema='eyex_backend')
    op.drop_table('workspace_members', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_usage_records_workspace_id'), table_name='usage_records', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_usage_records_recorded_at'), table_name='usage_records', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_usage_records_id'), table_name='usage_records', schema='eyex_backend')
    op.drop_table('usage_records', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_task_executions_workspace_id'), table_name='task_executions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_task_executions_status'), table_name='task_executions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_task_executions_session_id'), table_name='task_executions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_task_executions_id'), table_name='task_executions', schema='eyex_backend')
    op.drop_table('task_executions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_onboarding_tasks_onboarding_id'), table_name='onboarding_tasks', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_onboarding_tasks_id'), table_name='onboarding_tasks', schema='eyex_backend')
    op.drop_table('onboarding_tasks', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_invoices_subscription_id'), table_name='invoices', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_invoices_organization_id'), table_name='invoices', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_invoices_id'), table_name='invoices', schema='eyex_backend')
    op.drop_table('invoices', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_api_keys_workspace_id'), table_name='api_keys', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_api_keys_id'), table_name='api_keys', schema='eyex_backend')
    op.drop_table('api_keys', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_configs_workspace_id'), table_name='agent_configs', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_configs_id'), table_name='agent_configs', schema='eyex_backend')
    op.drop_table('agent_configs', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_workspaces_slug'), table_name='workspaces', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_workspaces_organization_id'), table_name='workspaces', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_workspaces_id'), table_name='workspaces', schema='eyex_backend')
    op.drop_table('workspaces', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_subscriptions_organization_id'), table_name='subscriptions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_subscriptions_id'), table_name='subscriptions', schema='eyex_backend')
    op.drop_table('subscriptions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_sales_predictions_org_id'), table_name='sales_predictions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_sales_predictions_id'), table_name='sales_predictions', schema='eyex_backend')
    op.drop_table('sales_predictions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_organization_members_id'), table_name='organization_members', schema='eyex_backend')
    op.drop_table('organization_members', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_demos_scheduled_at'), table_name='enterprise_demos', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_demos_org_id'), table_name='enterprise_demos', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_demos_id'), table_name='enterprise_demos', schema='eyex_backend')
    op.drop_table('enterprise_demos', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_deal_activities_id'), table_name='deal_activities', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_deal_activities_deal_id'), table_name='deal_activities', schema='eyex_backend')
    op.drop_table('deal_activities', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_onboarding_org_id'), table_name='customer_onboarding', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_onboarding_id'), table_name='customer_onboarding', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_onboarding_current_stage'), table_name='customer_onboarding', schema='eyex_backend')
    op.drop_table('customer_onboarding', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_pipeline_deals_status'), table_name='pipeline_deals', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_pipeline_deals_stage'), table_name='pipeline_deals', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_pipeline_deals_org_id'), table_name='pipeline_deals', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_pipeline_deals_lead_id'), table_name='pipeline_deals', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_pipeline_deals_id'), table_name='pipeline_deals', schema='eyex_backend')
    op.drop_table('pipeline_deals', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_partnership_integrations_partner_id'), table_name='partnership_integrations', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_partnership_integrations_id'), table_name='partnership_integrations', schema='eyex_backend')
    op.drop_table('partnership_integrations', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_organizations_slug'), table_name='organizations', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_organizations_id'), table_name='organizations', schema='eyex_backend')
    op.drop_table('organizations', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_pricing_org_id'), table_name='enterprise_pricing', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_pricing_id'), table_name='enterprise_pricing', schema='eyex_backend')
    op.drop_table('enterprise_pricing', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_users_id'), table_name='users', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_users_email'), table_name='users', schema='eyex_backend')
    op.drop_table('users', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_usage_metrics_org_id'), table_name='usage_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_usage_metrics_id'), table_name='usage_metrics', schema='eyex_backend')
    op.drop_table('usage_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_usage_based_billing_org_id'), table_name='usage_based_billing', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_usage_based_billing_id'), table_name='usage_based_billing', schema='eyex_backend')
    op.drop_table('usage_based_billing', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_subscription_plans_slug'), table_name='subscription_plans', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_subscription_plans_id'), table_name='subscription_plans', schema='eyex_backend')
    op.drop_table('subscription_plans', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_roi_calculators_org_id'), table_name='roi_calculators', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_roi_calculators_id'), table_name='roi_calculators', schema='eyex_backend')
    op.drop_table('roi_calculators', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_retention_workflows_org_id'), table_name='retention_workflows', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_retention_workflows_id'), table_name='retention_workflows', schema='eyex_backend')
    op.drop_table('retention_workflows', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_partners_status'), table_name='partners', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_partners_partner_type'), table_name='partners', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_partners_id'), table_name='partners', schema='eyex_backend')
    op.drop_table('partners', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_marketplace_revenue_org_id'), table_name='marketplace_revenue', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_marketplace_revenue_id'), table_name='marketplace_revenue', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_marketplace_revenue_agent_id'), table_name='marketplace_revenue', schema='eyex_backend')
    op.drop_table('marketplace_revenue', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_market_opportunities_id'), table_name='market_opportunities', schema='eyex_backend')
    op.drop_table('market_opportunities', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_leads_status'), table_name='leads', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_leads_id'), table_name='leads', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_leads_email'), table_name='leads', schema='eyex_backend')
    op.drop_table('leads', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_industry_solutions_industry'), table_name='industry_solutions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_industry_solutions_id'), table_name='industry_solutions', schema='eyex_backend')
    op.drop_table('industry_solutions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_success_reports_org_id'), table_name='customer_success_reports', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_success_reports_id'), table_name='customer_success_reports', schema='eyex_backend')
    op.drop_table('customer_success_reports', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_health_status'), table_name='customer_health', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_health_org_id'), table_name='customer_health', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_health_id'), table_name='customer_health', schema='eyex_backend')
    op.drop_table('customer_health', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_feedback_org_id'), table_name='customer_feedback', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_customer_feedback_id'), table_name='customer_feedback', schema='eyex_backend')
    op.drop_table('customer_feedback', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_case_studies_org_id'), table_name='case_studies', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_case_studies_industry'), table_name='case_studies', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_case_studies_id'), table_name='case_studies', schema='eyex_backend')
    op.drop_table('case_studies', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_business_impact_measurements_org_id'), table_name='business_impact_measurements', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_business_impact_measurements_id'), table_name='business_impact_measurements', schema='eyex_backend')
    op.drop_table('business_impact_measurements', schema='eyex_backend')
    # ### end Alembic commands ###
