"""add memory and trust tables

Revision ID: d18005b29214
Revises: 10ba86abea77
Create Date: 2026-07-20 15:48:22.298008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd18005b29214'
down_revision: Union[str, None] = '10ba86abea77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_health_checks',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('check_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_health_checks_agent_id'), 'agent_health_checks', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_health_checks_id'), 'agent_health_checks', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_health_checks_org_id'), 'agent_health_checks', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_health_checks_status'), 'agent_health_checks', ['status'], unique=False, schema='eyex_backend')
    op.create_table('agent_memory',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'agent_name', 'key', name='uq_agent_memory_key'),
    schema='eyex_backend'
    )
    op.create_index('idx_agent_mem_lookup', 'agent_memory', ['session_id', 'agent_name'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_memory_id'), 'agent_memory', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_memory_org_id'), 'agent_memory', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_memory_session_id'), 'agent_memory', ['session_id'], unique=False, schema='eyex_backend')
    op.create_table('agent_performance_scores',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('speed_score', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('usefulness_score', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_performance_scores_agent_id'), 'agent_performance_scores', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_performance_scores_id'), 'agent_performance_scores', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_performance_scores_org_id'), 'agent_performance_scores', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('agent_recovery_actions',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_recovery_actions_agent_id'), 'agent_recovery_actions', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_recovery_actions_id'), 'agent_recovery_actions', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_recovery_actions_org_id'), 'agent_recovery_actions', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('agent_retirements',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_agent_id', sa.String(length=100), nullable=True),
    sa.Column('migration_notes', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_retirements_agent_id'), 'agent_retirements', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_retirements_id'), 'agent_retirements', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_retirements_org_id'), 'agent_retirements', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('agent_templates',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('template_type', sa.String(length=100), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_connectors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_templates_id'), 'agent_templates', ['id'], unique=False, schema='eyex_backend')
    op.create_table('agent_versions',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_versions_id'), 'agent_versions', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_versions_org_id'), 'agent_versions', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('ai_action_requests',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposed_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_ai_action_requests_agent_id'), 'ai_action_requests', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_action_requests_id'), 'ai_action_requests', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_action_requests_org_id'), 'ai_action_requests', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_action_requests_status'), 'ai_action_requests', ['status'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_action_requests_workspace_id'), 'ai_action_requests', ['workspace_id'], unique=False, schema='eyex_backend')
    op.create_table('ai_approval_workflows',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_action_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger_risk_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_ai_approval_workflows_id'), 'ai_approval_workflows', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_approval_workflows_org_id'), 'ai_approval_workflows', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('ai_governance_policies',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_type', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('action_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('require_explanation', sa.Boolean(), nullable=False),
    sa.Column('require_human_review', sa.Boolean(), nullable=False),
    sa.Column('approver_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_auto_approve_value', sa.Float(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_ai_governance_policies_id'), 'ai_governance_policies', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_governance_policies_org_id'), 'ai_governance_policies', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('ai_performance_metrics',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_ai_performance_metrics_agent_id'), 'ai_performance_metrics', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_performance_metrics_id'), 'ai_performance_metrics', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_performance_metrics_org_id'), 'ai_performance_metrics', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('business_impact_metrics',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('metric_category', sa.String(length=100), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=False),
    sa.Column('financial_value', sa.Float(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_business_impact_metrics_id'), 'business_impact_metrics', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_business_impact_metrics_org_id'), 'business_impact_metrics', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('certified_agents',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('certification_status', sa.String(length=50), nullable=False),
    sa.Column('certified_by', sa.UUID(), nullable=True),
    sa.Column('certified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certification_level', sa.String(length=50), nullable=False),
    sa.Column('compliance_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_certified_agents_agent_id'), 'certified_agents', ['agent_id'], unique=True, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_certified_agents_id'), 'certified_agents', ['id'], unique=False, schema='eyex_backend')
    op.create_table('conversation_messages',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index('idx_conv_session_created', 'conversation_messages', ['session_id', 'created_at'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_conversation_messages_id'), 'conversation_messages', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_conversation_messages_org_id'), 'conversation_messages', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False, schema='eyex_backend')
    op.create_table('data_isolation_rules',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=256), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('allowed_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('denied_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_data_isolation_rules_id'), 'data_isolation_rules', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_data_isolation_rules_org_id'), 'data_isolation_rules', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('decision_improvement_metrics',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('decisions_supported', sa.Integer(), nullable=False),
    sa.Column('decisions_improved', sa.Integer(), nullable=False),
    sa.Column('avg_confidence_before', sa.Float(), nullable=False),
    sa.Column('avg_confidence_after', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_decision_improvement_metrics_id'), 'decision_improvement_metrics', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_decision_improvement_metrics_org_id'), 'decision_improvement_metrics', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('developer_applications',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('developer_name', sa.String(length=256), nullable=False),
    sa.Column('developer_email', sa.String(length=320), nullable=False),
    sa.Column('application_status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('portfolio', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_developer_applications_id'), 'developer_applications', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_developer_applications_org_id'), 'developer_applications', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('encryption_keys',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key_name', sa.String(length=200), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_encryption_keys_id'), 'encryption_keys', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_encryption_keys_org_id'), 'encryption_keys', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('enterprise_connectors',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('connector_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auth_method', sa.String(length=100), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_enterprise_connectors_connector_type'), 'enterprise_connectors', ['connector_type'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_enterprise_connectors_id'), 'enterprise_connectors', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_enterprise_connectors_org_id'), 'enterprise_connectors', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_enterprise_connectors_status'), 'enterprise_connectors', ['status'], unique=False, schema='eyex_backend')
    op.create_table('identity_providers',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_identity_providers_id'), 'identity_providers', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_identity_providers_org_id'), 'identity_providers', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('long_term_memory',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'key', name='uq_long_term_memory_key'),
    schema='eyex_backend'
    )
    op.create_index('idx_ltm_session_type', 'long_term_memory', ['session_id', 'memory_type'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_long_term_memory_id'), 'long_term_memory', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_long_term_memory_org_id'), 'long_term_memory', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_long_term_memory_session_id'), 'long_term_memory', ['session_id'], unique=False, schema='eyex_backend')
    op.create_table('organization_knowledge',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'category', 'key', name='uq_org_knowledge_key'),
    schema='eyex_backend'
    )
    op.create_index('idx_org_knowledge_cat', 'organization_knowledge', ['org_id', 'category'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_organization_knowledge_id'), 'organization_knowledge', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_organization_knowledge_org_id'), 'organization_knowledge', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('proactive_alerts',
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_agent', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index('idx_alerts_org_type', 'proactive_alerts', ['org_id', 'alert_type'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_proactive_alerts_id'), 'proactive_alerts', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_proactive_alerts_org_id'), 'proactive_alerts', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('risk_prevention_metrics',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('risk_category', sa.String(length=100), nullable=False),
    sa.Column('risks_identified', sa.Integer(), nullable=False),
    sa.Column('risks_mitigated', sa.Integer(), nullable=False),
    sa.Column('potential_loss_avoided', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_risk_prevention_metrics_id'), 'risk_prevention_metrics', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_risk_prevention_metrics_org_id'), 'risk_prevention_metrics', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('security_alerts',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_security_alerts_alert_type'), 'security_alerts', ['alert_type'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_security_alerts_id'), 'security_alerts', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_security_alerts_org_id'), 'security_alerts', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_security_alerts_severity'), 'security_alerts', ['severity'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_security_alerts_status'), 'security_alerts', ['status'], unique=False, schema='eyex_backend')
    op.create_table('time_saved_metrics',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('manual_hours', sa.Float(), nullable=False),
    sa.Column('ai_hours', sa.Float(), nullable=False),
    sa.Column('hours_saved', sa.Float(), nullable=False),
    sa.Column('frequency_per_month', sa.Integer(), nullable=False),
    sa.Column('annual_value', sa.Float(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_time_saved_metrics_id'), 'time_saved_metrics', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_time_saved_metrics_org_id'), 'time_saved_metrics', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('workflow_reliability_metrics',
    sa.Column('workflow_name', sa.String(length=200), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('retried_executions', sa.Integer(), nullable=False),
    sa.Column('avg_duration_ms', sa.Float(), nullable=False),
    sa.Column('p95_duration_ms', sa.Float(), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_workflow_reliability_metrics_id'), 'workflow_reliability_metrics', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_workflow_reliability_metrics_org_id'), 'workflow_reliability_metrics', ['org_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_workflow_reliability_metrics_workflow_name'), 'workflow_reliability_metrics', ['workflow_name'], unique=False, schema='eyex_backend')
    op.create_table('agent_deployments',
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deployed_by', sa.UUID(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('traffic_percent', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['eyex_backend.agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_deployments_agent_version_id'), 'agent_deployments', ['agent_version_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_deployments_id'), 'agent_deployments', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_deployments_org_id'), 'agent_deployments', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('agent_test_runs',
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('test_suite', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['eyex_backend.agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_agent_test_runs_agent_version_id'), 'agent_test_runs', ['agent_version_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_agent_test_runs_id'), 'agent_test_runs', ['id'], unique=False, schema='eyex_backend')
    op.create_table('ai_approval_decisions',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['eyex_backend.ai_action_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_ai_approval_decisions_id'), 'ai_approval_decisions', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_ai_approval_decisions_request_id'), 'ai_approval_decisions', ['request_id'], unique=False, schema='eyex_backend')
    op.create_table('connector_credentials',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(length=100), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['eyex_backend.enterprise_connectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_connector_credentials_connector_id'), 'connector_credentials', ['connector_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_connector_credentials_id'), 'connector_credentials', ['id'], unique=False, schema='eyex_backend')
    op.create_table('explainable_ai_reports',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_explanation', sa.Text(), nullable=True),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['eyex_backend.ai_action_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_explainable_ai_reports_agent_id'), 'explainable_ai_reports', ['agent_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_explainable_ai_reports_id'), 'explainable_ai_reports', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_explainable_ai_reports_org_id'), 'explainable_ai_reports', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('human_review_tasks',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['eyex_backend.ai_action_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_human_review_tasks_id'), 'human_review_tasks', ['id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_human_review_tasks_org_id'), 'human_review_tasks', ['org_id'], unique=False, schema='eyex_backend')
    op.create_table('integration_syncs',
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['eyex_backend.enterprise_connectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='eyex_backend'
    )
    op.create_index(op.f('ix_eyex_backend_integration_syncs_connector_id'), 'integration_syncs', ['connector_id'], unique=False, schema='eyex_backend')
    op.create_index(op.f('ix_eyex_backend_integration_syncs_id'), 'integration_syncs', ['id'], unique=False, schema='eyex_backend')
    op.drop_table('test_conn', schema='eyex_backend')
    op.drop_table('test_table3', schema='eyex_backend')
    op.drop_table('test_table2', schema='eyex_backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table2',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    schema='eyex_backend'
    )
    op.create_table('test_table3',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    schema='eyex_backend'
    )
    op.create_table('test_conn',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    schema='eyex_backend'
    )
    op.drop_index(op.f('ix_eyex_backend_integration_syncs_id'), table_name='integration_syncs', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_integration_syncs_connector_id'), table_name='integration_syncs', schema='eyex_backend')
    op.drop_table('integration_syncs', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_human_review_tasks_org_id'), table_name='human_review_tasks', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_human_review_tasks_id'), table_name='human_review_tasks', schema='eyex_backend')
    op.drop_table('human_review_tasks', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_explainable_ai_reports_org_id'), table_name='explainable_ai_reports', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_explainable_ai_reports_id'), table_name='explainable_ai_reports', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_explainable_ai_reports_agent_id'), table_name='explainable_ai_reports', schema='eyex_backend')
    op.drop_table('explainable_ai_reports', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_connector_credentials_id'), table_name='connector_credentials', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_connector_credentials_connector_id'), table_name='connector_credentials', schema='eyex_backend')
    op.drop_table('connector_credentials', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_approval_decisions_request_id'), table_name='ai_approval_decisions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_approval_decisions_id'), table_name='ai_approval_decisions', schema='eyex_backend')
    op.drop_table('ai_approval_decisions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_test_runs_id'), table_name='agent_test_runs', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_test_runs_agent_version_id'), table_name='agent_test_runs', schema='eyex_backend')
    op.drop_table('agent_test_runs', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_deployments_org_id'), table_name='agent_deployments', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_deployments_id'), table_name='agent_deployments', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_deployments_agent_version_id'), table_name='agent_deployments', schema='eyex_backend')
    op.drop_table('agent_deployments', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_workflow_reliability_metrics_workflow_name'), table_name='workflow_reliability_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_workflow_reliability_metrics_org_id'), table_name='workflow_reliability_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_workflow_reliability_metrics_id'), table_name='workflow_reliability_metrics', schema='eyex_backend')
    op.drop_table('workflow_reliability_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_time_saved_metrics_org_id'), table_name='time_saved_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_time_saved_metrics_id'), table_name='time_saved_metrics', schema='eyex_backend')
    op.drop_table('time_saved_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_security_alerts_status'), table_name='security_alerts', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_security_alerts_severity'), table_name='security_alerts', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_security_alerts_org_id'), table_name='security_alerts', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_security_alerts_id'), table_name='security_alerts', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_security_alerts_alert_type'), table_name='security_alerts', schema='eyex_backend')
    op.drop_table('security_alerts', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_risk_prevention_metrics_org_id'), table_name='risk_prevention_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_risk_prevention_metrics_id'), table_name='risk_prevention_metrics', schema='eyex_backend')
    op.drop_table('risk_prevention_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_proactive_alerts_org_id'), table_name='proactive_alerts', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_proactive_alerts_id'), table_name='proactive_alerts', schema='eyex_backend')
    op.drop_index('idx_alerts_org_type', table_name='proactive_alerts', schema='eyex_backend')
    op.drop_table('proactive_alerts', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_organization_knowledge_org_id'), table_name='organization_knowledge', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_organization_knowledge_id'), table_name='organization_knowledge', schema='eyex_backend')
    op.drop_index('idx_org_knowledge_cat', table_name='organization_knowledge', schema='eyex_backend')
    op.drop_table('organization_knowledge', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_long_term_memory_session_id'), table_name='long_term_memory', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_long_term_memory_org_id'), table_name='long_term_memory', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_long_term_memory_id'), table_name='long_term_memory', schema='eyex_backend')
    op.drop_index('idx_ltm_session_type', table_name='long_term_memory', schema='eyex_backend')
    op.drop_table('long_term_memory', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_identity_providers_org_id'), table_name='identity_providers', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_identity_providers_id'), table_name='identity_providers', schema='eyex_backend')
    op.drop_table('identity_providers', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_connectors_status'), table_name='enterprise_connectors', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_connectors_org_id'), table_name='enterprise_connectors', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_connectors_id'), table_name='enterprise_connectors', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_enterprise_connectors_connector_type'), table_name='enterprise_connectors', schema='eyex_backend')
    op.drop_table('enterprise_connectors', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_encryption_keys_org_id'), table_name='encryption_keys', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_encryption_keys_id'), table_name='encryption_keys', schema='eyex_backend')
    op.drop_table('encryption_keys', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_developer_applications_org_id'), table_name='developer_applications', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_developer_applications_id'), table_name='developer_applications', schema='eyex_backend')
    op.drop_table('developer_applications', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_decision_improvement_metrics_org_id'), table_name='decision_improvement_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_decision_improvement_metrics_id'), table_name='decision_improvement_metrics', schema='eyex_backend')
    op.drop_table('decision_improvement_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_data_isolation_rules_org_id'), table_name='data_isolation_rules', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_data_isolation_rules_id'), table_name='data_isolation_rules', schema='eyex_backend')
    op.drop_table('data_isolation_rules', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_conversation_messages_session_id'), table_name='conversation_messages', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_conversation_messages_org_id'), table_name='conversation_messages', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_conversation_messages_id'), table_name='conversation_messages', schema='eyex_backend')
    op.drop_index('idx_conv_session_created', table_name='conversation_messages', schema='eyex_backend')
    op.drop_table('conversation_messages', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_certified_agents_id'), table_name='certified_agents', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_certified_agents_agent_id'), table_name='certified_agents', schema='eyex_backend')
    op.drop_table('certified_agents', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_business_impact_metrics_org_id'), table_name='business_impact_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_business_impact_metrics_id'), table_name='business_impact_metrics', schema='eyex_backend')
    op.drop_table('business_impact_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_performance_metrics_org_id'), table_name='ai_performance_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_performance_metrics_id'), table_name='ai_performance_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_performance_metrics_agent_id'), table_name='ai_performance_metrics', schema='eyex_backend')
    op.drop_table('ai_performance_metrics', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_governance_policies_org_id'), table_name='ai_governance_policies', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_governance_policies_id'), table_name='ai_governance_policies', schema='eyex_backend')
    op.drop_table('ai_governance_policies', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_approval_workflows_org_id'), table_name='ai_approval_workflows', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_approval_workflows_id'), table_name='ai_approval_workflows', schema='eyex_backend')
    op.drop_table('ai_approval_workflows', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_action_requests_workspace_id'), table_name='ai_action_requests', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_action_requests_status'), table_name='ai_action_requests', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_action_requests_org_id'), table_name='ai_action_requests', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_action_requests_id'), table_name='ai_action_requests', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_ai_action_requests_agent_id'), table_name='ai_action_requests', schema='eyex_backend')
    op.drop_table('ai_action_requests', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_versions_org_id'), table_name='agent_versions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_versions_id'), table_name='agent_versions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_versions_agent_id'), table_name='agent_versions', schema='eyex_backend')
    op.drop_table('agent_versions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_templates_id'), table_name='agent_templates', schema='eyex_backend')
    op.drop_table('agent_templates', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_retirements_org_id'), table_name='agent_retirements', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_retirements_id'), table_name='agent_retirements', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_retirements_agent_id'), table_name='agent_retirements', schema='eyex_backend')
    op.drop_table('agent_retirements', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_recovery_actions_org_id'), table_name='agent_recovery_actions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_recovery_actions_id'), table_name='agent_recovery_actions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_recovery_actions_agent_id'), table_name='agent_recovery_actions', schema='eyex_backend')
    op.drop_table('agent_recovery_actions', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_performance_scores_org_id'), table_name='agent_performance_scores', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_performance_scores_id'), table_name='agent_performance_scores', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_performance_scores_agent_id'), table_name='agent_performance_scores', schema='eyex_backend')
    op.drop_table('agent_performance_scores', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_memory_session_id'), table_name='agent_memory', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_memory_org_id'), table_name='agent_memory', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_memory_id'), table_name='agent_memory', schema='eyex_backend')
    op.drop_index('idx_agent_mem_lookup', table_name='agent_memory', schema='eyex_backend')
    op.drop_table('agent_memory', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_health_checks_status'), table_name='agent_health_checks', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_health_checks_org_id'), table_name='agent_health_checks', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_health_checks_id'), table_name='agent_health_checks', schema='eyex_backend')
    op.drop_index(op.f('ix_eyex_backend_agent_health_checks_agent_id'), table_name='agent_health_checks', schema='eyex_backend')
    op.drop_table('agent_health_checks', schema='eyex_backend')
    # ### end Alembic commands ###
